#!/bin/sh
#
# fluxbox startup-script:
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "$HOME/.Xmodmap"
xscreensaver -nosplash &
klipper &  # Needed for copying text from vim
ksuperkey -e 'Control_L=Escape;Super_L=Alt_L|F2'  # execute fbrun
/usr/bin/gnome-keyring-daemon --start --components=secrets &  # for nm-applet
nm-applet &
terminator &
conky -c ~/.conkyrc -d
conky -c ~/.conkycal -d
idesk &  # desktop icons
exec fluxbox -log "/home/amro/.fluxbox/log"

