#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/amro/.Xmodmap"

xscreensaver -nosplash &
conky -c ~/.conkyrc &
conky -c ~/.conkycal &

# for some reason need to start conky twice
# for the background to set - only one instance will be running
idesk &
idesk &

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/amro/.fluxbox/log"

