#!/bin/sh
#
# fluxbox startup-script:
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "$HOME/.Xmodmap"
xscreensaver -nosplash &
klipper &  # Needed for copying text from vim
ksuperkey -e 'Control_L=Escape;Super_L=Alt_L|F2'  # execute fbrun
/usr/bin/gnome-keyring-daemon --start --components=secrets &  # for nm-applet
while true; do nm-applet; done &
pa-applet &
insync start &
dropbox &
terminator &
conky -c ~/.conkyrc -d
conky -c ~/.conkycal -d
conky -c ~/.conkyprogA -d
conky -c ~/.conkyprogB -d
conky -c ~/.conkyprogC -d
conky -c ~/.conkyprogT -d
idesk &  # desktop icons
fbset "$HOME"/.idesktop/images.70.jpg &
exec fluxbox -log "$HOME/.fluxbox/log"

