# vim: fdm=marker
# shellcheck disable=SC1091,SC1090

# So that scp doesn't break
if [[ "$TERM" != "dumb" ]]; then
  source ~/.bashrc_real
fi
export TMOUT=$tmout

export PATH=/usr/local/opt/gnu-which/libexec/gnubin:/usr/local/opt/findutils/libexec/gnubin:$PATH
export PATH="/usr/local/opt/grep/libexec/gnubin:$PATH"
export PATH=/usr/local/tflint/bin:$PATH
export PATH="/usr/local/opt/make/libexec/gnubin:$PATH"

complete -C /usr/local/Cellar/terraform/0.11.14/bin/terraform terraform
